[platformio]
default_envs = zone-a

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7.0.4
  marcoschwartz/LiquidCrystal_I2C@^1.1.4
build_flags =
  -DMQTT_PORT=1883
  -DMQTT_HOST='"broker.hivemq.com"'

[env:zone-a]
build_flags =
  ${env.build_flags}
  -DNODE_ID='"zone-a"'
