[wokwi]
version = 1
firmware = ".pio/build/zone-a/firmware.bin"
elf = ".pio/build/zone-a/firmware.elf"
gdbServerPort = 3333

[wokwi.simulation]
speed = "full"

[[wokwi.uart]]
index = 0
baud = 115200

[[wokwi.network]]
host = "broker.hivemq.com"
port = 1883
