[wokwi]
version = 1
firmware = ".pio/build/edge-rl-node/firmware.bin"
elf = ".pio/build/edge-rl-node/firmware.elf"
gdbServerPort = 3333

[wokwi.simulation]
speed = "1MHz"

[[wokwi.uart]]
index = 0
baud = 115200

[[wokwi.network]]
host = "host.wokwi.internal"
port = 1883
