[platformio]
default_envs = zone-a, zone-b

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7.0.4
build_flags =
  -DMQTT_PORT=1883
  -DMQTT_HOST='"host.wokwi.internal"'

[env:zone-a]
build_flags =
  ${env.build_flags}
  -DNODE_ID='"zone-a"'

[env:zone-b]
build_flags =
  ${env.build_flags}
  -DNODE_ID='"zone-b"'
